backend = "glx";

# Window opacity

inactive-opacity = 0.90;
active-opacity = 0.90;
frame-opacity = 0.90;
opacity-rule = ["100:fullscreen"];

# Window background blur

blur: {
  method = "dual_kawase";
  strength = 1;
  background = false;
  background-frame = false;
  background-fixed = false;
}

# Window shadows

shadow = true;
shadow-radius = 20;
shadow-opacity = 0.9;
shadow-offset-x = -19;
shadow-offset-y = -19;
